#! /usr/bin/env bash

# List all configuration files to be linked
# They should be name exactly like they would be in $HOME,
# but not hidden.
CONFIG_FILES=(
    emacs
    gitconfig
    zprofile
    zshrc
    zsh.d
)

SUB_CONFIG_FILES=$(ls config)

# Get the config path
pushd $(dirname $0) > /dev/null
CONFIG_PATH=$(pwd)
popd > /dev/null

echo "[+] Linking configuration from $CONFIG_PATH to $HOME:"

cd $HOME
echo

# Link all configuration files
for file in ${CONFIG_FILES[@]}; do
    ln -fhs $CONFIG_PATH/$file .$file
    echo "    .$file"
done

for file in ${SUB_CONFIG_FILES[@]}; do
    ln -fhs $CONFIG_PATH/config/$file .config/$file
    echo "    .config/$file"
done

echo
echo "[+] Done"
