#! /usr/bin/env zsh

PYENV_ROOT="${HOME}/.pyenv"

PATH="\
${HOME}/bin:\
${HOME}/.yarn/bin:\
${HOME}/.config/yarn/global/node_modules/.bin:\
${HOME}/.local/bin:\
${PYENV_ROOT}/bin:\
/opt/homebrew/opt/openjdk/bin:\
${PATH}:"
