#! /usr/bin/env zsh

alias ls='ls -G'
alias l='ls -l'
alias ll='ls -lh'
alias la='ls -la'
alias du='du -h'
alias ne='emacs -nw'
alias cp='nocorrect cp'
alias mv='nocorrect mv -v'
alias rm='rm -v'
alias mkdir='nocorrect mkdir'
alias grep='grep --color=auto'
alias less='less -R'
alias reload="source ${HOME}/.zshrc"
