#! /usr/bin/env zsh

bindkey -e

autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end

bindkey "\e[A" history-beginning-search-backward-end
bindkey "\e[B" history-beginning-search-forward-end

bindkey '^?' backward-delete-char
bindkey '^[[3~' delete-char
