#! /usr/bin/env zsh

# Load fnm
if command -v fnm 1>/dev/null 2>&1
then
  eval "$(fnm env --use-on-cd --shell zsh --corepack-enabled --resolve-engines)"
fi

# Load pyenv
if command -v pyenv 1>/dev/null 2>&1
then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi

# Load starship
if command -v starship 1>/dev/null 2>&1
then
  eval "$(starship init zsh)"
fi
