#! /usr/bin/env zsh

# Load NVM:
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Load Pyenv:
if command -v pyenv 1>/dev/null 2>&1
then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi

# Load starship
if command -v starship 1>/dev/null 2>&1
then
  eval "$(starship init zsh)"
fi